# Generated by Django 3.1.3 on 2020-12-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='clasifplu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
